# Generated by Django 4.2.11 on 2024-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='', max_length=20),
        ),
    ]
