# Generated by Django 4.2.11 on 2024-04-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApi', '0004_alter_fooditem_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='foodApi.category'),
        ),
    ]
