# Generated by Django 4.2.11 on 2024-06-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApi', '0005_alter_fooditem_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodApi.category'),
        ),
    ]
